### PR TITLE
Un-register all the bot commands when the bot shuts down.

### PR DESCRIPTION
**Pull request by R3D4CTED**
When testing on production, the testing bots tend to clog up the command list when they're offline, causing confusion to users. This PR unregisters the slash/application commands whenever the bot is shut down, so that end-users don't have any confusion.

### CODE REVIEW

**Comment by R3D4CTED** [comment]
Note: It takes about a minute or two for the bot to completely shut down now, as commands are removed one-by-one. Does not work with Visual Studio Code debug mode for some reason.

**Comment by braxton** [comment]
IMO, this should only apply to non-prod versions of the bot. Given that the prod bot does important logging, we should minimise its downtime as much as possible.

We also definitely need to resolve the VSCode debug mode issues before merging since most (if not all) of the Chiya team use it to varying degrees.

**Comment by lunarmint** [comment]
I agree that this branch should not be merged, but should be kept around for local testing to unload the slash commands when needed as it takes way too long to completely shut off or reload the bot.

**Review by braxton — CHANGES_REQUESTED** [review]
This PR needs to check if the bot is being deployed for production. You may want to implement this via a env var that can be set in the docker-compose file.

**Pull request closed without merging**
