### PR TITLE
Support stickers in starboard embed

### PR DESCRIPTION
**Pull request by Kapppa**
Show all stickers and attach as image if the only image.

### CODE REVIEW

**Comment by lunarmint** [comment]
A few issues:
1. This does not work if you send a mix of attachments (especially image) of different types together with the sticker.
2. Stickers does not necessarily come in only png format. Refer to [here](https://docs.pycord.dev/en/master/api.html?highlight=sticker#discord.StickerFormatType).
3. I personally found the logic is lengthy and clunky. You cannot send multiple stickers at once so iterating through the stickers are not necessary. The flow control variable `has_image` is also not the most pythonic way to implement this.

**Comment by Kapppa** [comment]
The issue is that the image extension for lottie is json. Are you sure embeds support that as the image?

[See](https://github.com/Pycord-Development/pycord/blob/master/discord/enums.py#L548-L560) for the extensions. APNG and PNG both return png.

**Comment by lunarmint** [comment]
> 

The embed does not support it, indeed. If you star one, it should return an embed without content, which, I think is totally fine since it still has the jump url and everything else.

**Comment by Kapppa** [comment]
The embed is also unable to play the animated APNG. This is a know discord limitation. They only recently added support APNG in the main message. But embeds were overlooked, so we will have to deal with the static image. I tried the cdn. and media. urls both were static. I think in its current form it would fine.

For the multiple stickers. I saw that it was list so I assumed in some cases that you were able to send multiple, that maybe the case. But I have been unable to send multiple messages. So I think in its current form it is good.

**Review by lunarmint — APPROVED** [review]

**Pull request merged**
